In [1]:
import datetime

In [2]:
date = datetime.date(year = 2023, month =2, day =12)
time = datetime.time(hour=23, minute = 32, second =5, microsecond = 1234)

In [3]:
time

datetime.time(23, 32, 5, 1234)

In [4]:
dt = datetime.datetime(year =2023, month =2, day=12, hour=23, minute=32,second= 5, microsecond=1234 )

In [5]:
dt

datetime.datetime(2023, 2, 12, 23, 32, 5, 1234)

In [6]:
td  =datetime.timedelta(days = 5, hours = 5)

In [7]:
td

datetime.timedelta(days=5, seconds=18000)

In [8]:
print(date+td)

2023-02-17

In [9]:
print(dt + td)

2023-02-18 04:32:05.001234

In [12]:
import pandas as pd
pd.to_datetime('2023-2-12')

Timestamp('2023-02-12 00:00:00')

In [13]:
pd.to_datetime('2023-13-2')

ParserError: month must be in 1..12: 2023-13-2 present at position 0

In [14]:
a= pd.Series([10,20,30,40])

In [15]:
pd.to_datetime(a,unit='D') #the integer values in the Series 'a' are interpreted as numbers of days.

0   1970-01-11
1   1970-01-21
2   1970-01-31
3   1970-02-10
dtype: datetime64[ns]

In [16]:
df = pd.Series(['2023-2-13','13-2-2023','2023/2/13','40/5/2023'])

In [17]:
df

0    2023-2-13
1    13-2-2023
2    2023/2/13
3    40/5/2023
dtype: object

In [18]:
pd.to_datetime(df,errors='coerce')

C:\Users\Admin\AppData\Local\Temp\ipykernel_82464\3943228070.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  pd.to_datetime(df,errors='coerce')

0   2023-02-13
1   2023-02-13
2   2023-02-13
3          NaT
dtype: datetime64[ns]

In [19]:
crime = pd.read_csv('crime.csv')

In [20]:
crime

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,REPORTED_DATE,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,0,traffic-accident-dui-duid,traffic-accident,2014-06-29 2:01,-105.000149,39.745753,cbd,0,1
1,1,vehicular-eluding-no-chase,all-other-crimes,2014-06-29 1:54,-104.884660,39.738702,east-colfax,1,0
2,2,disturbing-the-peace,public-disorder,2014-06-29 2:00,-105.020719,39.706674,athmar-park,1,0
3,3,curfew,public-disorder,2014-06-29 2:18,-105.001552,39.769505,sunnyside,1,0
4,4,aggravated-assault,aggravated-assault,2014-06-29 4:17,-105.018557,39.679229,college-view-south-platte,1,0
...,...,...,...,...,...,...,...,...,...
460906,460906,burglary-business-by-force,burglary,2017-09-13 5:48,-105.033840,39.762365,west-highland,1,0
460907,460907,weapon-unlawful-discharge-of,all-other-crimes,2017-09-12 20:37,-105.040313,39.721264,barnum-west,1,0
460908,460908,traf-habitual-offender,all-other-crimes,2017-09-12 16:32,-104.847024,39.779596,montbello,1,0
460909,460909,criminal-mischief-other,public-disorder,2017-09-12 13:04,-104.949183,39.756353,skyland,1,0
460910,460910,theft-other,larceny,2017-09-12 9:30,-104.985739,39.735045,capitol-hill,1,0

In [21]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460911 entries, 0 to 460910
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           460911 non-null  int64
 1   OFFENSE_TYPE_ID      460911 non-null  object
 2   OFFENSE_CATEGORY_ID  460911 non-null  object
 3   REPORTED_DATE        460911 non-null  object
 4   GEO_LON              457296 non-null  float64
 5   GEO_LAT              457296 non-null  float64
 6   NEIGHBORHOOD_ID      460911 non-null  object
 7   IS_CRIME             460911 non-null  int64
 8   IS_TRAFFIC           460911 non-null  int64
dtypes: float64(2), int64(3), object(4)
memory usage: 31.6+ MB

In [22]:
crime['REPORTED_DATE'] = pd.to_datetime(crime['REPORTED_DATE'])

In [23]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460911 entries, 0 to 460910
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           460911 non-null  int64
 1   OFFENSE_TYPE_ID      460911 non-null  object
 2   OFFENSE_CATEGORY_ID  460911 non-null  object
 3   REPORTED_DATE        460911 non-null  datetime64[ns]
 4   GEO_LON              457296 non-null  float64
 5   GEO_LAT              457296 non-null  float64
 6   NEIGHBORHOOD_ID      460911 non-null  object
 7   IS_CRIME             460911 non-null  int64
 8   IS_TRAFFIC           460911 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(3)
memory usage: 31.6+ MB

In [24]:
crime_df = crime.set_index('REPORTED_DATE')

In [25]:
crime_df

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2014-06-29 02:01:00,0,traffic-accident-dui-duid,traffic-accident,-105.000149,39.745753,cbd,0,1
2014-06-29 01:54:00,1,vehicular-eluding-no-chase,all-other-crimes,-104.884660,39.738702,east-colfax,1,0
2014-06-29 02:00:00,2,disturbing-the-peace,public-disorder,-105.020719,39.706674,athmar-park,1,0
2014-06-29 02:18:00,3,curfew,public-disorder,-105.001552,39.769505,sunnyside,1,0
2014-06-29 04:17:00,4,aggravated-assault,aggravated-assault,-105.018557,39.679229,college-view-south-platte,1,0
...,...,...,...,...,...,...,...,...
2017-09-13 05:48:00,460906,burglary-business-by-force,burglary,-105.033840,39.762365,west-highland,1,0
2017-09-12 20:37:00,460907,weapon-unlawful-discharge-of,all-other-crimes,-105.040313,39.721264,barnum-west,1,0
2017-09-12 16:32:00,460908,traf-habitual-offender,all-other-crimes,-104.847024,39.779596,montbello,1,0
2017-09-12 13:04:00,460909,criminal-mischief-other,public-disorder,-104.949183,39.756353,skyland,1,0
2017-09-12 09:30:00,460910,theft-other,larceny,-104.985739,39.735045,capitol-hill,1,0

In [26]:
crime_df

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2014-06-29 02:01:00,0,traffic-accident-dui-duid,traffic-accident,-105.000149,39.745753,cbd,0,1
2014-06-29 01:54:00,1,vehicular-eluding-no-chase,all-other-crimes,-104.884660,39.738702,east-colfax,1,0
2014-06-29 02:00:00,2,disturbing-the-peace,public-disorder,-105.020719,39.706674,athmar-park,1,0
2014-06-29 02:18:00,3,curfew,public-disorder,-105.001552,39.769505,sunnyside,1,0
2014-06-29 04:17:00,4,aggravated-assault,aggravated-assault,-105.018557,39.679229,college-view-south-platte,1,0
...,...,...,...,...,...,...,...,...
2017-09-13 05:48:00,460906,burglary-business-by-force,burglary,-105.033840,39.762365,west-highland,1,0
2017-09-12 20:37:00,460907,weapon-unlawful-discharge-of,all-other-crimes,-105.040313,39.721264,barnum-west,1,0
2017-09-12 16:32:00,460908,traf-habitual-offender,all-other-crimes,-104.847024,39.779596,montbello,1,0
2017-09-12 13:04:00,460909,criminal-mischief-other,public-disorder,-104.949183,39.756353,skyland,1,0
2017-09-12 09:30:00,460910,theft-other,larceny,-104.985739,39.735045,capitol-hill,1,0

In [27]:
crime_df.loc['2017']

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-05-22 14:41:00,7261,traffic-accident,traffic-accident,-104.673812,39.849292,dia,0,1
2017-05-17 20:35:00,7262,threats-to-injure,public-disorder,-105.020053,39.694351,ruby-hill,1,0
2017-06-07 07:47:00,7265,burglary-residence-by-force,burglary,-104.981677,39.763597,five-points,1,0
2017-05-26 16:46:00,7270,theft-other,larceny,-104.839119,39.769694,stapleton,1,0
2017-06-07 07:42:00,7272,criminal-trespassing,all-other-crimes,-104.673812,39.849292,dia,1,0
...,...,...,...,...,...,...,...,...
2017-09-13 05:48:00,460906,burglary-business-by-force,burglary,-105.033840,39.762365,west-highland,1,0
2017-09-12 20:37:00,460907,weapon-unlawful-discharge-of,all-other-crimes,-105.040313,39.721264,barnum-west,1,0
2017-09-12 16:32:00,460908,traf-habitual-offender,all-other-crimes,-104.847024,39.779596,montbello,1,0
2017-09-12 13:04:00,460909,criminal-mischief-other,public-disorder,-104.949183,39.756353,skyland,1,0
2017-09-12 09:30:00,460910,theft-other,larceny,-104.985739,39.735045,capitol-hill,1,0

In [28]:
crime_df.loc['2017-09-12']

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-09-12 15:59:00,134270,traffic-accident,traffic-accident,-104.940906,39.742085,city-park,0,1
2017-09-12 01:33:00,450816,criminal-mischief-mtr-veh,public-disorder,-105.001564,39.749800,union-station,1,0
2017-09-12 00:37:00,451067,theft-other,larceny,-104.954910,39.717317,cherry-creek,1,0
2017-09-12 02:45:00,451094,theft-of-motor-vehicle,auto-theft,-105.009236,39.686194,ruby-hill,1,0
2017-09-12 04:59:00,451100,theft-of-motor-vehicle,auto-theft,-105.039597,39.785489,regis,1,0
...,...,...,...,...,...,...,...,...
2017-09-12 14:00:00,460905,forgery-poss-of-forged-inst,white-collar-crime,-104.991137,39.785432,globeville,1,0
2017-09-12 20:37:00,460907,weapon-unlawful-discharge-of,all-other-crimes,-105.040313,39.721264,barnum-west,1,0
2017-09-12 16:32:00,460908,traf-habitual-offender,all-other-crimes,-104.847024,39.779596,montbello,1,0
2017-09-12 13:04:00,460909,criminal-mischief-other,public-disorder,-104.949183,39.756353,skyland,1,0
2017-09-12 09:30:00,460910,theft-other,larceny,-104.985739,39.735045,capitol-hill,1,0

In [29]:
crime_df.loc['Dec 2015']

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2015-12-18 23:51:00,1213,theft-of-motor-vehicle,auto-theft,-105.024694,39.708538,athmar-park,1,0
2015-12-06 11:14:00,1223,theft-other,larceny,-105.010653,39.764714,highland,1,0
2015-12-12 20:43:00,1224,burglary-residence-by-force,burglary,-104.916538,39.722582,hilltop,1,0
2015-12-16 14:19:00,1232,public-peace-other,public-disorder,-104.984492,39.730045,capitol-hill,1,0
2015-12-22 14:14:00,1294,traf-other,all-other-crimes,-104.970889,39.760751,whittier,1,0
...,...,...,...,...,...,...,...,...
2015-12-08 15:29:00,377881,assault-simple,other-crimes-against-persons,-105.039861,39.676497,harvey-park,1,0
2015-12-11 08:55:00,378674,assault-simple,other-crimes-against-persons,-105.001805,39.710870,athmar-park,1,0
2015-12-21 14:15:00,379078,assault-dv,other-crimes-against-persons,-104.873367,39.670668,hampden,1,0
2015-12-08 13:09:00,435956,fraud-identity-theft,white-collar-crime,-105.064441,39.654373,bear-valley,1,0
2015-12-24 13:56:00,442801,theft-other,larceny,-104.956983,39.665810,wellshire,1,0

In [30]:
crime_df.loc['2017'].sort_index()

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-01-01 00:16:00,344311,weapon-unlawful-discharge-of,all-other-crimes,-104.943494,39.769454,clayton,1,0
2017-01-01 00:27:00,344762,theft-other,larceny,-104.994496,39.747944,cbd,1,0
2017-01-01 01:16:00,370737,assault-simple,other-crimes-against-persons,-104.991384,39.753888,five-points,1,0
2017-01-01 01:16:00,370148,weapon-unlawful-discharge-of,all-other-crimes,-104.838218,39.794725,montbello,1,0
2017-01-01 01:20:00,345896,traf-other,all-other-crimes,-104.961459,39.772793,cole,1,0
...,...,...,...,...,...,...,...,...
2017-09-29 03:58:00,454304,burglary-business-by-force,burglary,-104.987803,39.681199,overland,1,0
2017-09-29 03:58:00,454315,traf-other,all-other-crimes,-104.994817,39.768043,globeville,1,0
2017-09-29 04:12:00,455301,drug-pcs-other-drug,drug-alcohol,-105.048416,39.726209,villa-park,1,0
2017-09-29 04:12:00,454656,traf-other,all-other-crimes,-105.006426,39.783139,sunnyside,1,0
2017-09-29 06:16:00,453457,theft-of-motor-vehicle,auto-theft,-104.890269,39.657222,hampden,1,0

In [31]:
crime_df.loc['2017-01-01':'2017-01-12'].sort_index()

C:\Users\Admin\AppData\Local\Temp\ipykernel_82464\4145696832.py:1: FutureWarning: Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is deprecated and will raise a KeyError in a future Version.
  crime_df.loc['2017-01-01':'2017-01-12'].sort_index()

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2017-01-01 00:16:00,344311,weapon-unlawful-discharge-of,all-other-crimes,-104.943494,39.769454,clayton,1,0
2017-01-01 00:27:00,344762,theft-other,larceny,-104.994496,39.747944,cbd,1,0
2017-01-01 01:16:00,370148,weapon-unlawful-discharge-of,all-other-crimes,-104.838218,39.794725,montbello,1,0
2017-01-01 01:16:00,370737,assault-simple,other-crimes-against-persons,-104.991384,39.753888,five-points,1,0
2017-01-01 01:20:00,345896,traf-other,all-other-crimes,-104.961459,39.772793,cole,1,0
...,...,...,...,...,...,...,...,...
2017-01-12 23:31:00,368339,robbery-street,robbery,-104.980087,39.781848,globeville,1,0
2017-01-12 23:40:00,356249,traf-other,all-other-crimes,-104.980400,39.740144,north-capitol-hill,1,0
2017-01-12 23:43:00,368337,traffic-accident,traffic-accident,-104.912622,39.761905,north-park-hill,0,1
2017-01-12 23:45:00,361687,traf-other,all-other-crimes,-105.025094,39.714977,barnum,1,0
2017-01-12 23:51:00,366635,traf-other,all-other-crimes,-105.025039,39.682269,harvey-park,1,0

In [32]:
crime_df.between_time('10:00','15:00').sort_index()

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2012-01-02 10:07:00,419591,traffic-accident,traffic-accident,-104.987420,39.744885,cbd,0,1
2012-01-02 10:21:00,430560,robbery-business,robbery,-104.987952,39.680818,overland,1,0
2012-01-02 10:55:00,73412,traffic-accident-hit-and-run,traffic-accident,-105.039614,39.718941,barnum,0,1
2012-01-02 11:05:00,41185,aggravated-assault,aggravated-assault,-104.884971,39.741441,east-colfax,1,0
2012-01-02 11:32:00,52674,theft-parts-from-vehicle,theft-from-motor-vehicle,-105.041071,39.699543,westwood,1,0
...,...,...,...,...,...,...,...,...
2017-09-28 14:37:00,453860,traffic-accident-hit-and-run,traffic-accident,-104.987378,39.743356,cbd,0,1
2017-09-28 14:37:00,455327,liquor-possession,drug-alcohol,-104.987310,39.753598,five-points,1,0
2017-09-28 14:43:00,453463,drug-methampetamine-sell,drug-alcohol,-104.987316,39.739243,capitol-hill,1,0
2017-09-28 14:58:00,453023,aggravated-assault,aggravated-assault,-104.937113,39.760998,north-park-hill,1,0
2017-09-28 15:00:00,453012,criminal-mischief-mtr-veh,public-disorder,-105.036416,39.709617,westwood,1,0

In [33]:
#원하는 시간만 추출
crime_df_sr= crime_df.at_time('17:12').sort_index()

In [34]:
crime_df_sr

,Unnamed: 0,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,,
2012-01-09 17:12:00,420025,traffic-accident-hit-and-run,traffic-accident,-104.967168,39.779882,elyria-swansea,0,1
2012-01-09 17:12:00,439227,theft-parts-from-vehicle,theft-from-motor-vehicle,-104.975118,39.732261,capitol-hill,1,0
2012-01-18 17:12:00,81577,traffic-accident,traffic-accident,-104.925475,39.667489,hampden,0,1
2012-01-21 17:12:00,76449,theft-other,larceny,-105.048940,39.759138,west-highland,1,0
2012-01-26 17:12:00,68229,theft-of-motor-vehicle,auto-theft,-105.007757,39.702934,athmar-park,1,0
...,...,...,...,...,...,...,...,...
2017-09-05 17:12:00,451976,traffic-accident-hit-and-run,traffic-accident,-104.941818,39.738320,congress-park,0,1
2017-09-19 17:12:00,459134,traffic-accident-hit-and-run,traffic-accident,-105.043091,39.769144,west-highland,0,1
2017-09-19 17:12:00,460153,traffic-accident,traffic-accident,-104.978179,39.747500,north-capitol-hill,0,1
2017-09-20 17:12:00,459766,drug-cocaine-possess,drug-alcohol,-104.886679,39.745784,east-colfax,1,0
2017-09-28 17:12:00,454671,criminal-trespassing,all-other-crimes,-104.988776,39.742805,cbd,1,0